### PR TITLE
Allow mac address param to be a NetAddr::MAC object

### PR DESCRIPTION
**Pull request by djzort**
As per the subject.

Includes test

### CODE REVIEW

**Comment by karenetheridge** [comment]
I've fixed the travis config in the repository. Please could you rebase your PR? (passing tests also require an entry to be added to the 'Changes' file.)

**Comment by djzort** [comment]
As requested, i have rebased and added an entry to Changes file. Let me know if theres anything else you need

**Comment by karenetheridge** [comment]
Thanks!
I'm going to change this so NetAddr::MAC is not a mandatory prereq, and then release shortly.

**Comment by djzort** [comment]
that makes sense  i think i botched up the dist.ini change. i wanted to say "use NetAddr::MAC in testing, but its no a prereq for install"

**Comment by karenetheridge** [comment]
No problem. I had to do another release after this one because the
Compress::* libraries were being accidentally added in too, something I
should have spotted a few weeks ago. Prerequisites are hard! :)

**Pull request merged**
